### ISSUE TITLE
Macrodocs.org seems to have disappeared

### ISSUE THREAD

**Issue by anadrome** [hubgit/macrodocs#1]
The main site and API at macrodocs.org seem to have disappeared. I noticed because that breaks some of the functionality of https://github.com/sckott/cites. Apologies if this is too obvious an issue that you're already aware of!

**Comment by hubgit** [comment]
It looks ok to me, currently - maybe a temporary issue?

**Comment by anadrome** [comment]
Weird! I'm just getting a DreamHost welcome page: "The DreamHost customer who owns macrodocs.org has not yet uploaded their website or has chosen to leave this holding page active." Tested from a remote machine as well, to make sure it wasn't just a local DNS issue. I'll check again in a bit to see if it fixes itself, though.

**Comment by hubgit** [comment]
Ah, yes, I'm seeing the same thing now - maybe a DNS issue, I'll investigate…
